Honor `getValue` method of ReflectionToStringBuilder & its subclasses to get the field value
apache/commons-lang pull request #1086
Opened 2023-07-24 18:01 UTC by shashankrnr32

Noticed this change recently which removed the usage of the method `getValue` to get the field value. The custom implementations of this class would never call the `getValue` method with custom implementations

@garydgregory

2023-08-14 12:32 UTC, garydgregory requested changes
Hi @shashankrnr32 
Thank you for your PR!
This PR missing a unit test to avoid a future regression.

2023-08-14 12:32 UTC, garydgregory commented on src/main/java/org/apache/commons/lang3/builder/ReflectionToStringBuilder.java
> -    protected Object getValue(final Field field) throws IllegalAccessException {
Why are you removing `IllegalAccessException`?

2023-08-15 17:13 UTC, shashankrnr32 commented
> Hi @shashankrnr32 Thank you for your PR! This PR missing a unit test to avoid a future regression.

@garydgregory Added `ReflectionToStringBuilderCustomImplementationTest` that overrides the `getValue` and modifies the generated field value by the base class. If this behaviour changes in the future, the test will break.

2023-08-26 22:37 UTC, garydgregory commented
https://issues.apache.org/jira/projects/LANG/issues/LANG-1710

2023-08-27 11:51 UTC, garydgregory commented on src/main/java/org/apache/commons/lang3/builder/ReflectionToStringBuilder.java
> -    protected Object getValue(final Field field) throws IllegalAccessException {
Hello @shashankrnr32 
Thank you for your update.
This PR attempts to restore compatibility with the `getValue()` method but changes that method's definition and breaks compatibility differently. For example, if I have a subclass that overrides `getValue()` using the released signature, that subclass will no longer compile if this patch is applied. The test in this PR does not reflect that a subclass can throw `IllegalAccessException` in the `getValue()` method signature, so the test is not checking for full compatibility. See git master for a fix.

2023-08-27 16:40 UTC, garydgregory commented
Closing, see the comment.

2023-08-27 16:40 UTC, closed without merging