add lastIndexOfAnyChar method just like indexOfAny
apache/commons-lang pull request #273
Opened 2017-06-29 12:55 UTC by qxo

2017-07-02 15:00 UTC, PascalSchumacher commented
Thanks for the pull request, but the build fails because of checkstyle violations, see: https://travis-ci.org/apache/commons-lang/jobs/248359934 for details.

2017-07-04 16:12 UTC, Abrasha commented
@PascalSchumacher will it be okay if I will fix warnings for the author?

2017-07-04 17:38 UTC, PascalSchumacher commented
@Abrasha You can create a pull request for @qxo fork. If he merges it, it will be added to this pull request.

2017-07-04 17:49 UTC, PascalSchumacher commented
@Abrasha  Thank you very much for the offer, but I think you should give @qxo some more time (a few days) to fix it himself.

2017-07-05 05:36 UTC, qxo commented
ok, I'll check it :)

2018-01-12 17:22 UTC, garydgregory requested changes
Thank you for the PR. Please review my comments.

2018-01-12 17:22 UTC, garydgregory commented on src/main/java/org/apache/commons/lang3/StringUtils.java
> +    public static int lastIndexOfAnyChar( final CharSequence cs,final char... searchChars) {
Fix formatting.

2018-01-12 17:22 UTC, garydgregory commented on src/main/java/org/apache/commons/lang3/StringUtils.java
> +     * <p>Search a CharSequence to find the last index of any
Use the active voice in Javadoc: "Returns...", "Searches...", "Gets..." and so on.

2018-01-12 17:22 UTC, garydgregory commented on src/test/java/org/apache/commons/lang3/StringUtilsEqualsIndexOfTest.java
> +        assertEquals(-1, StringUtils.lastIndexOfAnyChar(null, (char[]) null));
Maybe use INDEX_NOT_FOUND as a static import instead of -1...

2026-05-27 21:16 UTC, garydgregory commented
Closing, old PR, won't do.

2026-05-27 21:16 UTC, closed without merging