Use own validator ClassUtils.getSimpleName to get String input
apache/commons-lang pull request #758
Opened 2021-05-16 09:22 UTC by arturobernalg

2022-03-06 13:45 UTC, garydgregory commented
@arturobernalg Would you rebase on master please?

2022-03-06 15:55 UTC, arturobernalg commented
> @arturobernalg Would you rebase on master, please?

done
TY

2022-03-06 17:09 UTC, garydgregory requested changes
Please review all call sites keeping in mind the 2 comments I left in this PR. In general, it does not make sense to call the util method when the argument will never be null.

2022-03-06 17:09 UTC, garydgregory commented on src/main/java/org/apache/commons/lang3/time/FastDateParser.java
> +            return ClassUtils.getSimpleName(this) + " [pattern=" + pattern + "]";
We should not do this since a "this" will never be null.

2022-03-06 17:09 UTC, garydgregory commented on src/main/java/org/apache/commons/lang3/EnumUtils.java
> +            Integer.valueOf(constants.length), ClassUtils.getSimpleName(enumClass), Integer.valueOf(Long.SIZE));
This does not make sense since a null enumClass will cause an exception before we even get here.

2022-03-25 15:51 UTC, garydgregory requested changes
Hi @arturobernalg Ping?

2023-06-22 13:28 UTC, closed without merging