Add missing exception javadoc/tests for some null arguments
apache/commons-lang pull request #869
Opened 2022-03-26 15:07 UTC by dvmarcilio

Hello! I added some missing javadoc for null arguments and wrote tests when they didn't exist.
I tried to keep the diffs as small as possible and the sentences consistent.
I will be happy to change anything if needed. Thanks.

2022-03-26 17:52 UTC, garydgregory commented
Hi @dvmarcilio & thank you for your PR. Let' hold off on this one. I want to normalize on using Java's Objects#requireNonNull().

2022-07-05 14:40 UTC, garydgregory requested changes
Hello @dvmarcilio 
Thank you for your patience and PR. Please rebase on git master and review your PR with my comment in mind. 
TY!

2022-07-10 20:06 UTC, dvmarcilio commented
Hi @garydgregory. 
Thanks for pinging me. All should be fine now.

2022-07-10 21:49 UTC, kinow requested changes

2022-07-10 21:49 UTC, kinow commented on src/main/java/org/apache/commons/lang3/reflect/TypeUtils.java
> +     * @throws NullPointerException if either {@code rawClass} or {@code typeVariable}
`typeVariableMap` & `typeVariableMap`?

2022-07-11 07:12 UTC, dvmarcilio commented on src/main/java/org/apache/commons/lang3/reflect/TypeUtils.java
> +     * @throws NullPointerException if either {@code rawClass} or {@code typeVariable}
Oops. Thanks for finding it. Fixed it!

2023-02-11 15:38 UTC, merged